services:
  - type: web
    name: github-streak
    runtime: go
    buildCommand: go build -tags netgo -ldflags '-s -w' -o app ./cmd/server
    startCommand: ./app
    envVars:
      - key: SERVER_PORT
        value: 8080
      - key: APP_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: GITHUB_CALLBACK_URL
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
